name: "Setup"
description: "Setup environment"

inputs:
  node-version:
    description: "Node version to install"
    required: true
    default: lts/fermium

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/cache-restore
      with:
        node-version: ${{ inputs.node-version }}

    # Conditional steps not supported by composite actions. Also, the
    # installation step should only be executed during the setup
    - name: Install Dependencies
      # Syntax: steps.{{ id }}.outputs.cache-hit
      # See: https://www.jonathan-wilkinson.com/github-actions-cache-everything
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install
