name: "Setup"
description: "Setup and prepare the repo"

inputs:
  node-version:
    description: "Node version to install"
    required: true
    default: lts/fermium

runs:
  using: "composite"
  steps:
    # actions/setup-node: https://github.com/actions/setup-node
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        # # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
        # cache: "npm"
        # cache-dependency-path: "**/package-lock.json"

    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install
      shell: bash