name: "Cache restoration"
description: "Setup a NodeJS environment and restore cache if any, given a node version"

inputs:
  node-version:
    description: "Node version to use"
    required: true
    default: lts/*
outputs:
  cache-hit:
    description: "Forward actions/cache cache-hit output"
    value: ${{ steps.node-cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    # actions/setup-node: https://github.com/actions/setup-node
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        # # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
        # cache: "npm"
        # cache-dependency-path: "**/package-lock.json"

    - name: Cache Node Modules
      id: node-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        # For matrix strategy, include the node version in the cache key
        key: node-modules-${{ inputs.node-version }}-${{ hashFiles('package-lock.json') }}
