name: Chromatic

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # ---------- Initialise environment by installing the dependencies
  init:
    name: Initialise Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup
        with:
          node-version: lts/fermium

  # ---------- chromatic deployment
  chromatic-deployment:
    name: Chromatic deployment
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/cache-restore

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
