name: Chromatic

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # ---------- Initialise environment by installing the dependencies
  init:
    name: Initialise Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ./.github/actions/cache-restore
        id: node-cache
        with:
          node-version: lts/fermium

      # Conditional steps not supported by composite actions. Also, the
      # installation step should only be executed during the setup
      - name: Install Dependencies
        # Syntax: steps.{{ id }}.outputs.cache-hit
        # See: https://www.jonathan-wilkinson.com/github-actions-cache-everything
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

  # ---------- chromatic deployment
  chromatic-deployment:
    name: Chromatic deployment
    runs-on: ubuntu-latest
    needs: init

    steps:
      # Chromatic caveat when using checkout@v2:
      # https://www.chromatic.com/docs/github-actions#support-for-codeactionscheckoutv2code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - uses: ./.github/actions/cache-restore

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          buildScriptName: "storybook:build"
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
